spring:
  application:
    name: spring-boot-booklibrary-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/libDB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
  error:
    include-message: ALWAYS
application:
  issue:
    max-allowed-books: 2